### ISSUE TITLE
In iPhone 4 the title is above left and right buttons

### ISSUE THREAD

**Issue by nbastoWM** [react-native-fellowship/react-native-navbar#111]
In the simulator all appears fine but when I run it in an actual iPhone 4 the title is not aligned with the left or right buttons, it appears above.

**Comment by Kureev** [comment]
Well, AFAIK, iPhone 4 doesn't have a retina display, so that's why you have twice big bottom offset. 
Unfortunately, iPhone 4 has been discontinued by Apple, so I don't see any reason to fix anything to make it work.

But as a workaround, you can pass a custom title component and specify a padding that will work for you.
