### ISSUE TITLE
RN 0.16.0-rc support?

### ISSUE THREAD

**Issue by sankhadeeproy007** [react-native-fellowship/react-native-navbar#116]
Am I the only one who hasn't got it to work with RN 0.16.0-rc? 
I keep getting this error. Any help?

![screen shot 2015-12-02 at 7 16 09 pm](https://cloud.githubusercontent.com/assets/10998047/11532416/ad052984-9929-11e5-9b7a-b4b7ec5f54eb.png)

**Comment by Kureev** [comment]
Seems it needs to change `stage` in `.babelrc` as it described [here](http://babeljs.io/blog/2015/10/29/6.0.0/)

**TL;DR:**
> We also added presets for stages such as babel-preset-stage-0 (used to be stage: 0 in .babelrc in babel 5.x).

**Comment by chagasaway** [comment]
Just upgraded react-native version here to 0.16.0 and got the same error.

Is there any workaround?

**Comment by chetstone** [comment]
I wonder if .babelrc could just be removed? Could be that RN packager by default now enables any transforms needed by react-native-navbar.

**Comment by steveleec** [comment]
This is how I fixed it:
Babel specifies that there is a specific preset for React.
{
 "preset": "react"
}
Therefore, I changed .babelrc contained in react-native-navbar to this:
{
  "retainLines": true,
  "compact": true,
  "presets": ["react"], // or "preset": "react"
  "comments": false,
  "sourceMaps": false
}
I am not using white list anymore because all its elements are now under presets.

**Comment by Kureev** [comment]
Should be fixed in `1.1.x`, can TS verify and close the issue?

**Comment by sankhadeeproy007** [comment]
Hi @Kureev, I tried `1.1.1`, but I'm getting this error while build. I deleted my node_modules folder and tried again, but to no avail. Any help regarding this?
![screen shot 2015-12-14 at 1 16 34 pm](https://cloud.githubusercontent.com/assets/10998047/11775457/00ca3e8a-a265-11e5-9ccf-bdcbbd75e783.png)

**Comment by Kureev** [comment]
Well, `1.1.1` assumes you're using `npm3`, so you have a flat dependency tree and the error above can't occur. If you're using previous version of `npm` and don't want to upgrade, you can fork previous version and remove `.babelrc` to make it work in `npm2` and `babel 6`.

**Comment by grabbou** [comment]
> Well, 1.1.1 assumes you're using npm3

Why such constraint? How come you can assume `npm` version? AFAIK there are no deal-breaking changes between them.

I would like to note that there's not even a single reference to this module from the stack trace above, so it's related to npm3 and react-native itself. I went back to `npm2` because of the above (it does not make flat dependency tree in all cases, it only flattens when versions are matching as far as I know leaving other versions in original node_modules of a dependency which results in naming collision - had that with `react-tools` installed, `react` and `react-native` in one project (universal app).

**Comment by Kureev** [comment]
> Why such constraint? How come you can assume npm version? AFAIK there are no deal-breaking changes between them.

Because as you can see from above, @sankhadeeproy007 has an issue having 2 react libraries in different folders which are conflicting with each other. Anybody can use previous versions for `npm2`, from 1.1 I'm using `dependencies` instead of `peerDependencies`, and that's why it installs 2 versions of RN with `npm2`. 

I'm sorry for your experience with `npm3`, but that's how ecosystem moves forward. It's considered as a stable release, so I'll aim for it.

**Comment by grabbou** [comment]
Ha, to me - that's invalid https://github.com/react-native-fellowship/react-native-navbar/blob/master/package.json#L18. 

Why it's listed in dependencies, not `devDependencies` nor `peerDependencies` ? That's what everyone's been doing and works great w/o forcing versions.

Also - with such structure, `npm3` flat dependencies tree is not going to give you anything if I have 0.15 installed - I will end up with two copies anyway + no warning will be printed about different versions.

**Comment by Kureev** [comment]
Because `devDependencies` - dependencies for developing library itself. 
About `peerDependencies`:
```
We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically 
downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already 
installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run 
this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.
```

So, according to the paragraph above, I consider the best place for react-native lib is inside `dependencies` section.

**Comment by grabbou** [comment]
That's actually a good thing and documentation clearly describes the desired use-case for that: https://docs.npmjs.com/files/package.json#peerdependencies

As I said - listing that in `dependencies` assumes that `react-native-navbar` runs as a standalone module bundled with its own `react-native` version which is not true. 

By moving it to `dependencies` you are just replicating deprecated `peerDependencies` behaviour (so-called `autoinstalling`). As already commented above, it introduces silent conflicts with versions and naming conflicts (it's also slower to install because of two different react-native versions to compile). 

It's worth noting that the above set up is going to give duplicated versions almost all the time, why? Because for now, that plugin explicitly marks `^0.16` in dependencies. That means, for all users below 0.16 - it's not going to work (naming collision). Assuming everyone has upgraded and 0.17 is out - you bump it to 0.17 to make it working and then - it does not work for all the others that are on 0.16. That is just wrong ;)

To me, it should stay as `peerDependency` because that's not only what everyone is doing, but also what peerDependencies has been made for.

**Comment by Kureev** [comment]
> As already commented above, it introduces silent conflicts with versions and naming conflicts (it's also slower to install because of two different react-native versions to compile).

That's why I've added versions into requirements.

> It's worth noting that the above set up is going to give duplicated versions almost all the time, why? 
Use a prev. version of navbar for npm2.

> Because for now, that plugin explicitly marks ^0.16 in dependencies. That means, for all users below 0.16 - it's not going to work (naming collision)

They should use previous version. Babel 6 anyway wouldn't work with old RN.

> Assuming everyone has upgraded and 0.17 is out - you bump it to 0.17 to make it working and then - it does not work for all the others that are on 0.16

Yeah, probably it should be >= 0.16 instead

**Comment by grabbou** [comment]
>= doesn't change anything because it will always resolve to latest version available in registry. It doesn't work like peer dependencies where it resolves to already installed version. Which means you still get all the conflicts.

That plugin didn't change anything to adjust to Babel 6 apart from removing babelrc - it's going to work anyway because the same transformers were available anyway. 

Setting that in side menu repo is going to break all projects done with older React and not upgraded for instance which is a complete no-go. 

Version should be specified in perrDependencies if there are any constraints so there's at least warning. I can't see that approach to be valid in any case.

I can imagine it to work well with webpack and web where it can be deduped quite easily. But here the case is different.

**Comment by grabbou** [comment]
The thing is - if `npm3 install` or `npm2 dedupe` find matching semver versions in all package.json - they will be flattened, which works when all requirements are met. But in case they are not - we get hard to debug naming collision that is not as good as peerDependency warning.

**Comment by TangRufus** [comment]
Same error on react native 0.17.0, even with `.babelrc` files removed.

Any work around?

```
Error building DependencyGraph:
 Error: Naming collision detected: /Users/me/Documents/react-native/myApp/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js collides with /Users/me/Documents/react-native/myApp/node_modules/react-native-navbar/node_modules/react-native/Libraries/vendor/react/platformImplementations/universal/worker/UniversalWorkerNodeHandle.js
```

**Comment by Kureev** [comment]
Ok, that became annoying, so I just reverted `dependencies` back to `peerDependencies`. Released in `1.1.2`

**Comment by Kureev** [comment]
Ok, that became annoying, so I just reverted `dependencies` back to `peerDependencies`. Released in `1.1.2`

**Comment by grabbou** [comment]
VICTORYYY :+1:

**Comment by grabbou** [comment]
See #127
